### ISSUE TITLE
Something blows up highlighting

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#56] opened 2017-03-06 15:01 UTC
I'm on v1.14.3.

If you view this file, the selected section has blown up highlighting; unsure what exactly causes it: https://github.com/rakudo/rakudo/blob/9da50e352f899225ec805d59a834413307471ce6/src/core/IO/Spec/Win32.pm#L199-L216

### Picture [optional]
![untitled](https://cloud.githubusercontent.com/assets/5747918/23615242/c24846e8-0253-11e7-8850-e57d24ddffd4.png)

### Leave this in. For internal use.
- [ ] Fixed in Master
- [ ] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by samcv** [comment] 2017-04-15 05:09
Closing since #60 is better documented and both are caused by the same issue.

**Closed** 2017-04-15 05:09 UTC
